### PR TITLE
added_entities

### PR DESCRIPTION
**Pull request by tylerneu**
These changes add a method to retrieve the added `Entity` objects to a group.

### CODE REVIEW

**Comment by somewes** [comment]
@tylerneu can you give more context to what this is solving? there are already various methods to fetch entities in the group. is the intent here to only fetch entities if the group type is a static list of entities?

**Comment by tylerneu** [comment]
@somewes The intent is to fetch the entities that have been _added_ to the group (not the resulting _sub_ entities) in order to display the user's choices for later editing. We are currently doing this in multiple places and I believe something should be added here. I have not found an existing method to do this. 

Example, I'm creating a `List` of `MANAGER_A` & `TEAM_B` that will result in the employees in those groups but I need to be able to retrieve `MANAGER_A` & `TEAM_B` to display in an edit screen.

**Comment by tylerneu** [comment]
I'm also getting more information from the team about needing to get inactive `Entity` objects. I'm considering an `is_active` param to get inactive if needed.

**Comment by somewes** [comment]
for including inactive entities, you can update the membership api to accept an `is_active` param, then add some logic to query the entities based on the group membership configuration.

**Comment by somewes** [comment]
EntityGroup supports 3 different configurations of memberships. This is querying for 2 of the 3 types of configurations. If we add a method on EntityGroup to fetch entity references for memberships, it needs a better name. We have "all of a kind" "all kinds under an entity" and "specific entities". Maybe `get_membership_entities` is a better name, because it isn't fetching group entities, it is fetching entities referenced in the membership.

Other concerns - this doesn't allow any sort of bulk querying across multiple groups so if this is ever used in a serializer or data set with more than one group, it will be doing at least a query per object.

It seems more application-specific. "I want to fetch some specific data from 2 of the 3 types of membership configs and ignore the other config" It might make more sense just adding a wrapper method to query what you need.

Something like
```
def get_membership_entities(entity_group_ids, is_active=True):
    filter_args = dict(entity_group_id__in=entity_group_ids, entity_id__isnull=False)
    if is_active is not None:
        filter_args['entity__is_active'] = is_active
    memberships = EntityGroupMembership.objects.filter(**filter_args).select_related('entity')
    membership_entities = defaultdict(list)
    for membership in memberships:
        membership_entities[membership.entity_group_id].append(membership.entity)
    return membership_entities
```
although if you want to serialize that, you would want to break it up so you serialize all the entities at once, then add the serialized entities to the lists.

But as I mentioned earlier, since you are querying for a subset of info based on an application-specific use case, this might as well live elsewhere. Or else you can query the membership api and your code can ignore any memberships that have a null entity. You could add a filter to the membership api that just applies entity_isnull=False, then your code can pull the entity data

**Pull request closed without merging**
